### ISSUE TITLE
Some colors not controlled by "Styles" settings

### ISSUE THREAD

**Issue by awoimbee** [p2-inc/phasetwo-admin-portal#124]
Hi, 
I made an absolutely stunning color palette:
![stunning color palette](https://github.com/p2-inc/phasetwo-admin-portal/assets/22431493/1859fded-1e2b-444c-b97f-ed275ebbf363)

But sadly I still see a lot of default blue in the portal:
![portal still in blue](https://github.com/p2-inc/phasetwo-admin-portal/assets/22431493/e0375472-e9c0-49b3-9e7e-9026dffe7b73)

I noticed I could fix the issue using this CSS snippet:
```css
.border-primary-700 {
  border-color: #04e300 !important;
}
.border-primary-700:hover {
  border-color: #027300 !important;
}
* {
  --tw-gradient-to: #04e300 !important;
  --tw-gradient-from: #027300 !important;
}
```

But there is still one hardcoded color:
https://github.com/p2-inc/phasetwo-admin-portal/blob/4bb536ba0f2fe9392b03a791bcf271589a8f4f51/src/index.css#L15C18-L15C25
